using System;
using System.Collections.Generic;
using System.Linq;

// ReSharper disable InconsistentNaming

namespace CoreLib.Services
{
    public static class Catalog
    {
        public enum Countries
        {
            BD,
            BE,
            BF,
            BG,
            BA,
            BB,
            WF,
            BL,
            BM,
            BN,
            BO,
            BH,
            BI,
            BJ,
            BT,
            JM,
            BV,
            BW,
            WS,
            BQ,
            BR,
            BS,
            JE,
            BY,
            BZ,
            RU,
            RW,
            RS,
            TL,
            RE,
            TM,
            TJ,
            RO,
            TK,
            GW,
            GU,
            GT,
            GS,
            GR,
            GQ,
            GP,
            JP,
            GY,
            GG,
            GF,
            GE,
            GD,
            GB,
            GA,
            SV,
            GN,
            GM,
            GL,
            GI,
            GH,
            OM,
            TN,
            JO,
            HR,
            HT,
            HU,
            HK,
            HN,
            HM,
            VE,
            PR,
            PS,
            PW,
            PT,
            SJ,
            PY,
            IQ,
            PA,
            PF,
            PG,
            PE,
            PK,
            PH,
            PN,
            PL,
            PM,
            ZM,
            EH,
            EE,
            EG,
            ZA,
            EC,
            IT,
            VN,
            SB,
            ET,
            SO,
            ZW,
            SA,
            ES,
            ER,
            ME,
            MD,
            MG,
            MF,
            MA,
            MC,
            UZ,
            MM,
            ML,
            MO,
            MN,
            MH,
            MK,
            MU,
            MT,
            MW,
            MV,
            MQ,
            MP,
            MS,
            MR,
            IM,
            UG,
            TZ,
            MY,
            MX,
            IL,
            FR,
            IO,
            SH,
            FI,
            FJ,
            FK,
            FM,
            FO,
            NI,
            NL,
            NO,
            NA,
            VU,
            NC,
            NE,
            NF,
            NG,
            NZ,
            NP,
            NR,
            NU,
            CK,
            XK,
            CI,
            CH,
            CO,
            CN,
            CM,
            CL,
            CC,
            CA,
            CG,
            CF,
            CD,
            CZ,
            CY,
            CX,
            CR,
            CW,
            CV,
            CU,
            SZ,
            SY,
            SX,
            KG,
            KE,
            SS,
            SR,
            KI,
            KH,
            KN,
            KM,
            ST,
            SK,
            KR,
            SI,
            KP,
            KW,
            SN,
            SM,
            SL,
            SC,
            KZ,
            KY,
            SG,
            SE,
            SD,
            DO,
            DM,
            DJ,
            DK,
            VG,
            DE,
            YE,
            DZ,
            US,
            UY,
            YT,
            UM,
            LB,
            LC,
            LA,
            TV,
            TW,
            TT,
            TR,
            LK,
            LI,
            LV,
            TO,
            LT,
            LU,
            LR,
            LS,
            TH,
            TF,
            TG,
            TD,
            TC,
            LY,
            VA,
            VC,
            AE,
            AD,
            AG,
            AF,
            AI,
            VI,
            IS,
            IR,
            AM,
            AL,
            AO,
            AS,
            AR,
            AU,
            AT,
            AW,
            IN,
            AX,
            AZ,
            IE,
            ID,
            UA,
            QA,
            MZ,
            AQ
        }

        public enum Currencies
        {
            ANG,
            USD,
            BDT,
            EUR,
            XOF,
            BGN,
            BAM,
            BBD,
            XPF,
            BMD,
            BND,
            BOB,
            BHD,
            BIF,
            BTN,
            JMD,
            NOK,
            BWP,
            WST,
            BRL,
            BSD,
            GBP,
            BYN,
            BZD,
            RUB,
            RWF,
            RSD,
            TMT,
            TJS,
            RON,
            NZD,
            GTQ,
            XAF,
            JPY,
            GYD,
            GEL,
            XCD,
            GNF,
            GMD,
            DKK,
            GIP,
            GHS,
            OMR,
            TND,
            JOD,
            HRK,
            HTG,
            HUF,
            HKD,
            HNL,
            AUD,
            ILS,
            PYG,
            IQD,
            PAB,
            PGK,
            PEN,
            PKR,
            PHP,
            PLN,
            ZMW,
            MAD,
            EGP,
            ZAR,
            VND,
            SBD,
            ETB,
            SOS,
            SAR,
            ERN,
            MDL,
            MGA,
            UZS,
            MMK,
            MOP,
            MNT,
            MKD,
            MUR,
            MWK,
            MVR,
            UGX,
            TZS,
            MYR,
            MXN,
            SHP,
            FJD,
            FKP,
            NIO,
            NAD,
            VUV,
            NGN,
            NPR,
            CHF,
            COP,
            CNY,
            CLP,
            CAD,
            CDF,
            CZK,
            CRC,
            CVE,
            CUP,
            SZL,
            SYP,
            KGS,
            KES,
            SSP,
            SRD,
            KHR,
            KMF,
            STN,
            KRW,
            KWD,
            SLL,
            SCR,
            KZT,
            KYD,
            SGD,
            SEK,
            SDG,
            DOP,
            DJF,
            YER,
            DZD,
            UYU,
            LBP,
            LAK,
            TWD,
            TTD,
            TRY,
            LKR,
            TOP,
            LRD,
            LSL,
            THB,
            LYD,
            AED,
            AFN,
            ISK,
            IRR,
            AMD,
            ALL,
            AOA,
            ARS,
            AWG,
            INR,
            AZN,
            IDR,
            UAH,
            QAR,
            MZN,
            VES,
            MRU
        }

        public static IReadOnlyDictionary<Countries, Currencies> CountryCurrency = new Dictionary<Countries, Currencies>
        {
            {Countries.BD, Currencies.BDT},
            {Countries.BE, Currencies.EUR},
            {Countries.BF, Currencies.XOF},
            {Countries.BG, Currencies.BGN},
            {Countries.BA, Currencies.BAM},
            {Countries.BB, Currencies.BBD},
            {Countries.WF, Currencies.XPF},
            {Countries.BL, Currencies.EUR},
            {Countries.BM, Currencies.BMD},
            {Countries.BN, Currencies.BND},
            {Countries.BO, Currencies.BOB},
            {Countries.BH, Currencies.BHD},
            {Countries.BI, Currencies.BIF},
            {Countries.BJ, Currencies.XOF},
            {Countries.BT, Currencies.BTN},
            {Countries.JM, Currencies.JMD},
            {Countries.BV, Currencies.NOK},
            {Countries.BW, Currencies.BWP},
            {Countries.WS, Currencies.WST},
            {Countries.BQ, Currencies.USD},
            {Countries.BR, Currencies.BRL},
            {Countries.BS, Currencies.BSD},
            {Countries.JE, Currencies.GBP},
            {Countries.BY, Currencies.BYN},
            {Countries.BZ, Currencies.BZD},
            {Countries.RU, Currencies.RUB},
            {Countries.RW, Currencies.RWF},
            {Countries.RS, Currencies.RSD},
            {Countries.TL, Currencies.USD},
            {Countries.RE, Currencies.EUR},
            {Countries.TM, Currencies.TMT},
            {Countries.TJ, Currencies.TJS},
            {Countries.RO, Currencies.RON},
            {Countries.TK, Currencies.NZD},
            {Countries.GW, Currencies.XOF},
            {Countries.GU, Currencies.USD},
            {Countries.GT, Currencies.GTQ},
            {Countries.GS, Currencies.GBP},
            {Countries.GR, Currencies.EUR},
            {Countries.GQ, Currencies.XAF},
            {Countries.GP, Currencies.EUR},
            {Countries.JP, Currencies.JPY},
            {Countries.GY, Currencies.GYD},
            {Countries.GG, Currencies.GBP},
            {Countries.GF, Currencies.EUR},
            {Countries.GE, Currencies.GEL},
            {Countries.GD, Currencies.XCD},
            {Countries.GB, Currencies.GBP},
            {Countries.GA, Currencies.XAF},
            {Countries.SV, Currencies.USD},
            {Countries.GN, Currencies.GNF},
            {Countries.GM, Currencies.GMD},
            {Countries.GL, Currencies.DKK},
            {Countries.GI, Currencies.GIP},
            {Countries.GH, Currencies.GHS},
            {Countries.OM, Currencies.OMR},
            {Countries.TN, Currencies.TND},
            {Countries.JO, Currencies.JOD},
            {Countries.HR, Currencies.HRK},
            {Countries.HT, Currencies.HTG},
            {Countries.HU, Currencies.HUF},
            {Countries.HK, Currencies.HKD},
            {Countries.HN, Currencies.HNL},
            {Countries.HM, Currencies.AUD},
            {Countries.VE, Currencies.VES},
            {Countries.PR, Currencies.USD},
            {Countries.PS, Currencies.ILS},
            {Countries.PW, Currencies.USD},
            {Countries.PT, Currencies.EUR},
            {Countries.SJ, Currencies.NOK},
            {Countries.PY, Currencies.PYG},
            {Countries.IQ, Currencies.IQD},
            {Countries.PA, Currencies.PAB},
            {Countries.PF, Currencies.XPF},
            {Countries.PG, Currencies.PGK},
            {Countries.PE, Currencies.PEN},
            {Countries.PK, Currencies.PKR},
            {Countries.PH, Currencies.PHP},
            {Countries.PN, Currencies.NZD},
            {Countries.PL, Currencies.PLN},
            {Countries.PM, Currencies.EUR},
            {Countries.ZM, Currencies.ZMW},
            {Countries.EH, Currencies.MAD},
            {Countries.EE, Currencies.EUR},
            {Countries.EG, Currencies.EGP},
            {Countries.ZA, Currencies.ZAR},
            {Countries.EC, Currencies.USD},
            {Countries.IT, Currencies.EUR},
            {Countries.VN, Currencies.VND},
            {Countries.SB, Currencies.SBD},
            {Countries.ET, Currencies.ETB},
            {Countries.SO, Currencies.SOS},
            {Countries.ZW, Currencies.USD},
            {Countries.SA, Currencies.SAR},
            {Countries.ES, Currencies.EUR},
            {Countries.ER, Currencies.ERN},
            {Countries.ME, Currencies.EUR},
            {Countries.MD, Currencies.MDL},
            {Countries.MG, Currencies.MGA},
            {Countries.MF, Currencies.EUR},
            {Countries.MA, Currencies.MAD},
            {Countries.MC, Currencies.EUR},
            {Countries.UZ, Currencies.UZS},
            {Countries.MM, Currencies.MMK},
            {Countries.ML, Currencies.XOF},
            {Countries.MO, Currencies.MOP},
            {Countries.MN, Currencies.MNT},
            {Countries.MH, Currencies.USD},
            {Countries.MK, Currencies.MKD},
            {Countries.MU, Currencies.MUR},
            {Countries.MT, Currencies.EUR},
            {Countries.MW, Currencies.MWK},
            {Countries.MV, Currencies.MVR},
            {Countries.MQ, Currencies.EUR},
            {Countries.MP, Currencies.USD},
            {Countries.MS, Currencies.XCD},
            {Countries.MR, Currencies.MRU},
            {Countries.IM, Currencies.GBP},
            {Countries.UG, Currencies.UGX},
            {Countries.TZ, Currencies.TZS},
            {Countries.MY, Currencies.MYR},
            {Countries.MX, Currencies.MXN},
            {Countries.IL, Currencies.ILS},
            {Countries.FR, Currencies.EUR},
            {Countries.IO, Currencies.USD},
            {Countries.SH, Currencies.SHP},
            {Countries.FI, Currencies.EUR},
            {Countries.FJ, Currencies.FJD},
            {Countries.FK, Currencies.FKP},
            {Countries.FM, Currencies.USD},
            {Countries.FO, Currencies.DKK},
            {Countries.NI, Currencies.NIO},
            {Countries.NL, Currencies.EUR},
            {Countries.NO, Currencies.NOK},
            {Countries.NA, Currencies.NAD},
            {Countries.VU, Currencies.VUV},
            {Countries.NC, Currencies.XPF},
            {Countries.NE, Currencies.XOF},
            {Countries.NF, Currencies.AUD},
            {Countries.NG, Currencies.NGN},
            {Countries.NZ, Currencies.NZD},
            {Countries.NP, Currencies.NPR},
            {Countries.NR, Currencies.AUD},
            {Countries.NU, Currencies.NZD},
            {Countries.CK, Currencies.NZD},
            {Countries.XK, Currencies.EUR},
            {Countries.CI, Currencies.XOF},
            {Countries.CH, Currencies.CHF},
            {Countries.CO, Currencies.COP},
            {Countries.CN, Currencies.CNY},
            {Countries.CM, Currencies.XAF},
            {Countries.CL, Currencies.CLP},
            {Countries.CC, Currencies.AUD},
            {Countries.CA, Currencies.CAD},
            {Countries.CG, Currencies.XAF},
            {Countries.CF, Currencies.XAF},
            {Countries.CD, Currencies.CDF},
            {Countries.CZ, Currencies.CZK},
            {Countries.CY, Currencies.EUR},
            {Countries.CX, Currencies.AUD},
            {Countries.CR, Currencies.CRC},
            {Countries.CW, Currencies.ANG},
            {Countries.CV, Currencies.CVE},
            {Countries.CU, Currencies.CUP},
            {Countries.SZ, Currencies.SZL},
            {Countries.SY, Currencies.SYP},
            {Countries.SX, Currencies.ANG},
            {Countries.KG, Currencies.KGS},
            {Countries.KE, Currencies.KES},
            {Countries.SS, Currencies.SSP},
            {Countries.SR, Currencies.SRD},
            {Countries.KI, Currencies.AUD},
            {Countries.KH, Currencies.KHR},
            {Countries.KN, Currencies.XCD},
            {Countries.KM, Currencies.KMF},
            {Countries.ST, Currencies.STN},
            {Countries.SK, Currencies.EUR},
            {Countries.KR, Currencies.KRW},
            {Countries.SI, Currencies.EUR},
            {Countries.KP, Currencies.USD},
            {Countries.KW, Currencies.KWD},
            {Countries.SN, Currencies.XOF},
            {Countries.SM, Currencies.EUR},
            {Countries.SL, Currencies.SLL},
            {Countries.SC, Currencies.SCR},
            {Countries.KZ, Currencies.KZT},
            {Countries.KY, Currencies.KYD},
            {Countries.SG, Currencies.SGD},
            {Countries.SE, Currencies.SEK},
            {Countries.SD, Currencies.SDG},
            {Countries.DO, Currencies.DOP},
            {Countries.DM, Currencies.XCD},
            {Countries.DJ, Currencies.DJF},
            {Countries.DK, Currencies.DKK},
            {Countries.VG, Currencies.USD},
            {Countries.DE, Currencies.EUR},
            {Countries.YE, Currencies.YER},
            {Countries.DZ, Currencies.DZD},
            {Countries.US, Currencies.USD},
            {Countries.UY, Currencies.UYU},
            {Countries.YT, Currencies.EUR},
            {Countries.UM, Currencies.USD},
            {Countries.LB, Currencies.LBP},
            {Countries.LC, Currencies.XCD},
            {Countries.LA, Currencies.LAK},
            {Countries.TV, Currencies.AUD},
            {Countries.TW, Currencies.TWD},
            {Countries.TT, Currencies.TTD},
            {Countries.TR, Currencies.TRY},
            {Countries.LK, Currencies.LKR},
            {Countries.LI, Currencies.CHF},
            {Countries.LV, Currencies.EUR},
            {Countries.TO, Currencies.TOP},
            {Countries.LT, Currencies.EUR},
            {Countries.LU, Currencies.EUR},
            {Countries.LR, Currencies.LRD},
            {Countries.LS, Currencies.LSL},
            {Countries.TH, Currencies.THB},
            {Countries.TF, Currencies.EUR},
            {Countries.TG, Currencies.XOF},
            {Countries.TD, Currencies.XAF},
            {Countries.TC, Currencies.USD},
            {Countries.LY, Currencies.LYD},
            {Countries.VA, Currencies.EUR},
            {Countries.VC, Currencies.XCD},
            {Countries.AE, Currencies.AED},
            {Countries.AD, Currencies.EUR},
            {Countries.AG, Currencies.XCD},
            {Countries.AF, Currencies.AFN},
            {Countries.AI, Currencies.XCD},
            {Countries.VI, Currencies.USD},
            {Countries.IS, Currencies.ISK},
            {Countries.IR, Currencies.IRR},
            {Countries.AM, Currencies.AMD},
            {Countries.AL, Currencies.ALL},
            {Countries.AO, Currencies.AOA},
            {Countries.AS, Currencies.USD},
            {Countries.AR, Currencies.ARS},
            {Countries.AU, Currencies.AUD},
            {Countries.AT, Currencies.EUR},
            {Countries.AW, Currencies.AWG},
            {Countries.IN, Currencies.INR},
            {Countries.AX, Currencies.EUR},
            {Countries.AZ, Currencies.AZN},
            {Countries.IE, Currencies.EUR},
            {Countries.ID, Currencies.IDR},
            {Countries.UA, Currencies.UAH},
            {Countries.QA, Currencies.QAR},
            {Countries.MZ, Currencies.MZN},
            {Countries.AQ, Currencies.USD}
        };

        public static readonly IReadOnlyDictionary<Countries, string> CountriesNames = new Dictionary<Countries, string>
        {
            {Countries.BD, "Bangladesh"},
            {Countries.BE, "Belgium"},
            {Countries.BF, "Burkina Faso"},
            {Countries.BG, "Bulgaria"},
            {Countries.BA, "Bosnia and Herzegovina"},
            {Countries.BB, "Barbados"},
            {Countries.WF, "Wallis and Futuna"},
            {Countries.BL, "Saint Barthelemy"},
            {Countries.BM, "Bermuda"},
            {Countries.BN, "Brunei"},
            {Countries.BO, "Bolivia"},
            {Countries.BH, "Bahrain"},
            {Countries.BI, "Burundi"},
            {Countries.BJ, "Benin"},
            {Countries.BT, "Bhutan"},
            {Countries.JM, "Jamaica"},
            {Countries.BV, "Bouvet Island"},
            {Countries.BW, "Botswana"},
            {Countries.WS, "Samoa"},
            {Countries.BQ, "Bonaire, Saint Eustatius and Saba "},
            {Countries.BR, "Brazil"},
            {Countries.BS, "Bahamas"},
            {Countries.JE, "Jersey"},
            {Countries.BY, "Belarus"},
            {Countries.BZ, "Belize"},
            {Countries.RU, "Russia"},
            {Countries.RW, "Rwanda"},
            {Countries.RS, "Serbia"},
            {Countries.TL, "East Timor"},
            {Countries.RE, "Reunion"},
            {Countries.TM, "Turkmenistan"},
            {Countries.TJ, "Tajikistan"},
            {Countries.RO, "Romania"},
            {Countries.TK, "Tokelau"},
            {Countries.GW, "Guinea-Bissau"},
            {Countries.GU, "Guam"},
            {Countries.GT, "Guatemala"},
            {Countries.GS, "South Georgia and the South Sandwich Islands"},
            {Countries.GR, "Greece"},
            {Countries.GQ, "Equatorial Guinea"},
            {Countries.GP, "Guadeloupe"},
            {Countries.JP, "Japan"},
            {Countries.GY, "Guyana"},
            {Countries.GG, "Guernsey"},
            {Countries.GF, "French Guiana"},
            {Countries.GE, "Georgia"},
            {Countries.GD, "Grenada"},
            {Countries.GB, "United Kingdom"},
            {Countries.GA, "Gabon"},
            {Countries.SV, "El Salvador"},
            {Countries.GN, "Guinea"},
            {Countries.GM, "Gambia"},
            {Countries.GL, "Greenland"},
            {Countries.GI, "Gibraltar"},
            {Countries.GH, "Ghana"},
            {Countries.OM, "Oman"},
            {Countries.TN, "Tunisia"},
            {Countries.JO, "Jordan"},
            {Countries.HR, "Croatia"},
            {Countries.HT, "Haiti"},
            {Countries.HU, "Hungary"},
            {Countries.HK, "Hong Kong"},
            {Countries.HN, "Honduras"},
            {Countries.HM, "Heard Island and McDonald Islands"},
            {Countries.VE, "Venezuela"},
            {Countries.PR, "Puerto Rico"},
            {Countries.PS, "Palestinian Territory"},
            {Countries.PW, "Palau"},
            {Countries.PT, "Portugal"},
            {Countries.SJ, "Svalbard and Jan Mayen"},
            {Countries.PY, "Paraguay"},
            {Countries.IQ, "Iraq"},
            {Countries.PA, "Panama"},
            {Countries.PF, "French Polynesia"},
            {Countries.PG, "Papua New Guinea"},
            {Countries.PE, "Peru"},
            {Countries.PK, "Pakistan"},
            {Countries.PH, "Philippines"},
            {Countries.PN, "Pitcairn"},
            {Countries.PL, "Poland"},
            {Countries.PM, "Saint Pierre and Miquelon"},
            {Countries.ZM, "Zambia"},
            {Countries.EH, "Western Sahara"},
            {Countries.EE, "Estonia"},
            {Countries.EG, "Egypt"},
            {Countries.ZA, "South Africa"},
            {Countries.EC, "Ecuador"},
            {Countries.IT, "Italy"},
            {Countries.VN, "Vietnam"},
            {Countries.SB, "Solomon Islands"},
            {Countries.ET, "Ethiopia"},
            {Countries.SO, "Somalia"},
            {Countries.ZW, "Zimbabwe"},
            {Countries.SA, "Saudi Arabia"},
            {Countries.ES, "Spain"},
            {Countries.ER, "Eritrea"},
            {Countries.ME, "Montenegro"},
            {Countries.MD, "Moldova"},
            {Countries.MG, "Madagascar"},
            {Countries.MF, "Saint Martin"},
            {Countries.MA, "Morocco"},
            {Countries.MC, "Monaco"},
            {Countries.UZ, "Uzbekistan"},
            {Countries.MM, "Myanmar"},
            {Countries.ML, "Mali"},
            {Countries.MO, "Macao"},
            {Countries.MN, "Mongolia"},
            {Countries.MH, "Marshall Islands"},
            {Countries.MK, "Macedonia"},
            {Countries.MU, "Mauritius"},
            {Countries.MT, "Malta"},
            {Countries.MW, "Malawi"},
            {Countries.MV, "Maldives"},
            {Countries.MQ, "Martinique"},
            {Countries.MP, "Northern Mariana Islands"},
            {Countries.MS, "Montserrat"},
            {Countries.MR, "Mauritania"},
            {Countries.IM, "Isle of Man"},
            {Countries.UG, "Uganda"},
            {Countries.TZ, "Tanzania"},
            {Countries.MY, "Malaysia"},
            {Countries.MX, "Mexico"},
            {Countries.IL, "Israel"},
            {Countries.FR, "France"},
            {Countries.IO, "British Indian Ocean Territory"},
            {Countries.SH, "Saint Helena"},
            {Countries.FI, "Finland"},
            {Countries.FJ, "Fiji"},
            {Countries.FK, "Falkland Islands"},
            {Countries.FM, "Micronesia"},
            {Countries.FO, "Faroe Islands"},
            {Countries.NI, "Nicaragua"},
            {Countries.NL, "Netherlands"},
            {Countries.NO, "Norway"},
            {Countries.NA, "Namibia"},
            {Countries.VU, "Vanuatu"},
            {Countries.NC, "New Caledonia"},
            {Countries.NE, "Niger"},
            {Countries.NF, "Norfolk Island"},
            {Countries.NG, "Nigeria"},
            {Countries.NZ, "New Zealand"},
            {Countries.NP, "Nepal"},
            {Countries.NR, "Nauru"},
            {Countries.NU, "Niue"},
            {Countries.CK, "Cook Islands"},
            {Countries.XK, "Kosovo"},
            {Countries.CI, "Ivory Coast"},
            {Countries.CH, "Switzerland"},
            {Countries.CO, "Colombia"},
            {Countries.CN, "China"},
            {Countries.CM, "Cameroon"},
            {Countries.CL, "Chile"},
            {Countries.CC, "Cocos Islands"},
            {Countries.CA, "Canada"},
            {Countries.CG, "Republic of the Congo"},
            {Countries.CF, "Central African Republic"},
            {Countries.CD, "Democratic Republic of the Congo"},
            {Countries.CZ, "Czech Republic"},
            {Countries.CY, "Cyprus"},
            {Countries.CX, "Christmas Island"},
            {Countries.CR, "Costa Rica"},
            {Countries.CW, "Curacao"},
            {Countries.CV, "Cape Verde"},
            {Countries.CU, "Cuba"},
            {Countries.SZ, "Swaziland"},
            {Countries.SY, "Syria"},
            {Countries.SX, "Sint Maarten"},
            {Countries.KG, "Kyrgyzstan"},
            {Countries.KE, "Kenya"},
            {Countries.SS, "South Sudan"},
            {Countries.SR, "Suriname"},
            {Countries.KI, "Kiribati"},
            {Countries.KH, "Cambodia"},
            {Countries.KN, "Saint Kitts and Nevis"},
            {Countries.KM, "Comoros"},
            {Countries.ST, "Sao Tome and Principe"},
            {Countries.SK, "Slovakia"},
            {Countries.KR, "South Korea"},
            {Countries.SI, "Slovenia"},
            {Countries.KP, "North Korea"},
            {Countries.KW, "Kuwait"},
            {Countries.SN, "Senegal"},
            {Countries.SM, "San Marino"},
            {Countries.SL, "Sierra Leone"},
            {Countries.SC, "Seychelles"},
            {Countries.KZ, "Kazakhstan"},
            {Countries.KY, "Cayman Islands"},
            {Countries.SG, "Singapore"},
            {Countries.SE, "Sweden"},
            {Countries.SD, "Sudan"},
            {Countries.DO, "Dominican Republic"},
            {Countries.DM, "Dominica"},
            {Countries.DJ, "Djibouti"},
            {Countries.DK, "Denmark"},
            {Countries.VG, "British Virgin Islands"},
            {Countries.DE, "Germany"},
            {Countries.YE, "Yemen"},
            {Countries.DZ, "Algeria"},
            {Countries.US, "United States"},
            {Countries.UY, "Uruguay"},
            {Countries.YT, "Mayotte"},
            {Countries.UM, "United States Minor Outlying Islands"},
            {Countries.LB, "Lebanon"},
            {Countries.LC, "Saint Lucia"},
            {Countries.LA, "Laos"},
            {Countries.TV, "Tuvalu"},
            {Countries.TW, "Taiwan"},
            {Countries.TT, "Trinidad and Tobago"},
            {Countries.TR, "Turkey"},
            {Countries.LK, "Sri Lanka"},
            {Countries.LI, "Liechtenstein"},
            {Countries.LV, "Latvia"},
            {Countries.TO, "Tonga"},
            {Countries.LT, "Lithuania"},
            {Countries.LU, "Luxembourg"},
            {Countries.LR, "Liberia"},
            {Countries.LS, "Lesotho"},
            {Countries.TH, "Thailand"},
            {Countries.TF, "French Southern Territories"},
            {Countries.TG, "Togo"},
            {Countries.TD, "Chad"},
            {Countries.TC, "Turks and Caicos Islands"},
            {Countries.LY, "Libya"},
            {Countries.VA, "Vatican"},
            {Countries.VC, "Saint Vincent and the Grenadines"},
            {Countries.AE, "United Arab Emirates"},
            {Countries.AD, "Andorra"},
            {Countries.AG, "Antigua and Barbuda"},
            {Countries.AF, "Afghanistan"},
            {Countries.AI, "Anguilla"},
            {Countries.VI, "U.S. Virgin Islands"},
            {Countries.IS, "Iceland"},
            {Countries.IR, "Iran"},
            {Countries.AM, "Armenia"},
            {Countries.AL, "Albania"},
            {Countries.AO, "Angola"},
            {Countries.AS, "American Samoa"},
            {Countries.AR, "Argentina"},
            {Countries.AU, "Australia"},
            {Countries.AT, "Austria"},
            {Countries.AW, "Aruba"},
            {Countries.IN, "India"},
            {Countries.AX, "Aland Islands"},
            {Countries.AZ, "Azerbaijan"},
            {Countries.IE, "Ireland"},
            {Countries.ID, "Indonesia"},
            {Countries.UA, "Ukraine"},
            {Countries.QA, "Qatar"},
            {Countries.MZ, "Mozambique"},
            {Countries.AQ, "Antarctica"}
        };


        public enum PaymentTypes
        {
            ADVCASH,
            CASH_AT_ATM,
            CASH_DEPOSIT,
            CASHU,
            CREDITCARD,
            INTERNATIONAL_WIRE_SWIFT,
            MONEYBOOKERS,
            MONEYGRAM,
            NATIONAL_BANK,
            NETELLER,
            OKPAY,
            OTHER_ONLINE_WALLET,
            OTHER_REMITTANCE,
            OTHER,
            PAXUM,
            PAYEER,
            PAYONEER,
            PAYPAL,
            PAYZA,
            PERFECT_MONEY,
            RIA,
            SOLIDTRUSTPAY,
            SPECIFIC_BANK,
            TRANSFERWISE,
            WEBMONEY,
            WECHAT,
            WORLDREMIT,
            WU,
            QIWI,
            TELE2,
            YANDEXMONEY,
            LYDIA,
            MOBILEPAY_DANSKE_BANK_DK,
            INTERAC,
            VANILLA,
            ALIPAY,
            ASTROPAY,
            BANK_TRANSFER_IMPS,
            BITMAIN_COUPON,
            CASHIERS_CHECK,
            CHASE_QUICKPAY,
            DWOLLA,
            EASYPAISA,
            ECOCASH,
            GOOGLEWALLET,
            HAL_CASH,
            HYPERWALLET,
            MOBILEPAY_DANSKE_BANK,
            MPESA_KENYA,
            MPESA_TANZANIA,
            PAYM,
            PAYPALMYCASH,
            PAYTM,
            PINGIT,
            PostePay,
            PYC,
            RELOADIT,
            SERVE2SERVE,
            SQUARE_CASH,
            SUPERFLASH,
            SWISH,
            TELEGRAMATIC_ORDER,
            TIGOPESA_TANZANIA,
            VENMO,
            VIPPS,
            WALMART2WALMART,
            XOOM,
            ZELLE,
            QIWI_TERMINAL,
            SBERBANK,
            TINKOFF
        }
        

        public static IReadOnlyList<string> CountriesList => Enum.GetNames(typeof(Countries)).OrderBy(p => p).ToList();

        public static IReadOnlyList<string> CurrenciesList =>
            Enum.GetNames(typeof(Currencies)).OrderBy(p => p).ToList();

        public static IReadOnlyList<string> PaymentTypesList =>
            Enum.GetNames(typeof(PaymentTypes)).OrderBy(p => p).ToList();

        public static decimal AdMinAmount = 0.0001m;

        public enum CryptoExchangeVariables
        {
            bitstamp_usd,
            binance_usd,
            bkex_usd,
            mxc_usd,
            bittrex_usd,
            bitfinex_usd
        }

        public static IReadOnlyList<string> CryptoExchangeVariablesList => Enum.GetNames(typeof(CryptoExchangeVariables))
            .OrderBy(p => p).ToList();

        public static IReadOnlyList<string> AllVariablesList =>
            CryptoExchangeVariablesList.Concat(CurrenciesList).ToList();
    }
}