FROM debian:stable-slim
RUN apt update && apt install exim4-daemon-heavy -y && apt clean
EXPOSE 25 143
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]
CMD ["exim", "-C", "/etc/exim4/exim.conf",  "-bd", "-v", "-d+all"]

