FROM debian:stable-slim
RUN apt update && apt install spf-tools-perl exim4-daemon-heavy dovecot-common dovecot-imapd dovecot-managesieved dovecot-pgsql dovecot-pop3d dovecot-sieve gettext-base -y && apt clean
COPY start-prod.sh ./start.sh
RUN chmod +x ./start.sh
RUN mkdir /mail && chown mail:mail /mail && chmod 777 /mail && mkdir /var/run/dovecot && chown dovecot:dovecot /var/run/dovecot
EXPOSE 25 143
COPY ./tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]
CMD ["./start.sh"]

