image: docker

stages:
  - build
  - deploy_test


variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID

build_image:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

update_image:test:
  stage: deploy_test
  image: $COPMPOSER_UPDATER_TAG
  variables:
    STACK: front-test
    SERVICE: wordpress
    IMAGE_TAG_NAME: WORDPRESS_TAG
    GIT_STRATEGY: none
  when: manual
  timeout: 10 minutes
  script:
    - mkdir ~/.ssh && chmod 0700 ~/.ssh
    - >
      echo "Host $front_test_ip
        StrictHostKeyChecking no" > ~/.ssh/config
    - echo $docker_context_ssh_publick_key | base64 -d > ~/.ssh/id_rsa.pub
    - echo $docker_context_ssh_private_key | base64 -d > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa.pub
    - chmod 0600 ~/.ssh/id_rsa
    - docker context create front-test --docker "host=ssh://root@$front_test_ip"
    - docker --context front-test login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker --context front-test service update --with-registry-auth --image $IMAGE_TAG ${STACK}_$SERVICE
    - docker --context front-test logout $CI_REGISTRY
    - git clone http://gitlab-ci-token:$VERSIONS_TOKEN@gitlab:8100/root/versions.git
    - cd versions
    - sed -i "s|^$IMAGE_TAG_NAME=.*$|$IMAGE_TAG_NAME=$IMAGE_TAG|g" Test/.env
    - git add -A
    - git config --global user.email "$CI_PROJECT_NAME@gitlab" && git config --global user.name $CI_PROJECT_NAME
    - "git commit -m \"Update $CI_PROJECT_TITLE with image: $IMAGE_TAG\""
    - git push


update_mysql:test:
  stage: deploy_test
  image: $COPMPOSER_UPDATER_TAG
  when: manual
  timeout: 10 minutes
  script:
    - mkdir ~/.ssh && chmod 0700 ~/.ssh
    - >
      echo "Host $front_test_ip
        StrictHostKeyChecking no" > ~/.ssh/config
    - echo $docker_context_ssh_publick_key | base64 -d > ~/.ssh/id_rsa.pub
    - echo $docker_context_ssh_private_key | base64 -d > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa.pub
    - chmod 0600 ~/.ssh/id_rsa
    - docker context create front-test --docker "host=ssh://root@$front_test_ip"
    - cat dump | sed "s|___URL___|https://test.transbithub.com|g" > dump_test
    - CONTAINER=$(docker --context front-test ps --format "{{.Names}}" | grep mariadb)
    - docker --context front-test cp dump_test $CONTAINER:/
    - docker --context front-test exec $CONTAINER bash -c "MYSQL_PWD=wordpress mysql -u wordpress  wordpress < /dump_test"

