// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Aggregator.Services.Paxful.Json.Error;
//
//    var error = Error.FromJson(jsonString);

namespace Aggregator.Services.Paxful.Json.Error
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Error
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("timestamp")]
        public long Timestamp { get; set; }

        [JsonProperty("error")]
        public ErrorClass ErrorError { get; set; }
    }

    public partial class ErrorClass
    {
        [JsonProperty("code")]
        public long Code { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }
    }

    public partial class Error
    {
        public static Error FromJson(string json) => JsonConvert.DeserializeObject<Error>(json, Aggregator.Services.Paxful.Json.Error.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Error self) => JsonConvert.SerializeObject(self, Aggregator.Services.Paxful.Json.Error.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}