// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Aggregator.Services.Paxful.Json;
//
//    var offerJson = OfferJson.FromJson(jsonString);

namespace Aggregator.Services.Paxful.Json.OfferJson
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class OfferJson
    {
        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("timestamp")]
        public long Timestamp { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("offer_hash")]
        public string OfferHash { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("offer_id")]
        public string OfferId { get; set; }

        [JsonProperty("offer_type")]
        public string OfferType { get; set; }

        [JsonProperty("fiat_price_per_btc")]
        public decimal FiatPricePerBtc { get; set; }

        [JsonProperty("fiat_price_per_crypto")]
        public decimal FiatPricePerCrypto { get; set; }

        [JsonProperty("fiat_USD_price_per_btc")]
        public decimal FiatUsdPricePerBtc { get; set; }

        [JsonProperty("fiat_usd_price_per_crypto")]
        public decimal FiatUsdPricePerCrypto { get; set; }

        [JsonProperty("margin", NullValueHandling = NullValueHandling.Ignore)]
        public decimal Margin { get; set; }

        [JsonProperty("active")]
        public bool Active { get; set; }

        [JsonProperty("country_limitation_type", NullValueHandling = NullValueHandling.Ignore)]
        public object CountryLimitationType { get; set; }

        [JsonProperty("country_limitation_list", NullValueHandling = NullValueHandling.Ignore)]
        public object CountryLimitationList { get; set; }

        [JsonProperty("block_anonymizer_users", NullValueHandling = NullValueHandling.Ignore)]
        public bool BlockAnonymizerUsers { get; set; }

        [JsonProperty("fiat_amount_range_min")]
        public long FiatAmountRangeMin { get; set; }

        [JsonProperty("fiat_amount_range_max")]
        public long FiatAmountRangeMax { get; set; }

        [JsonProperty("predefined_amount", NullValueHandling = NullValueHandling.Ignore)]
        public object PredefinedAmount { get; set; }

        [JsonProperty("fee_percentage", NullValueHandling = NullValueHandling.Ignore)]
        public double FeePercentage { get; set; }

        [JsonProperty("crypto_min")]
        public long CryptoMin { get; set; }

        [JsonProperty("crypto_max")]
        public long CryptoMax { get; set; }

        [JsonProperty("offer_terms")]
        public string OfferTerms { get; set; }

        [JsonProperty("release_time", NullValueHandling = NullValueHandling.Ignore)]
        public object ReleaseTime { get; set; }

        [JsonProperty("payment_method_label", NullValueHandling = NullValueHandling.Ignore)]
        public string PaymentMethodLabel { get; set; }

        [JsonProperty("location_id")]
        public object LocationId { get; set; }

        [JsonProperty("payment_method_name")]
        public string PaymentMethodName { get; set; }

        [JsonProperty("payment_method_slug")]
        public string PaymentMethodSlug { get; set; }

        [JsonProperty("require_verified_email", NullValueHandling = NullValueHandling.Ignore)]
        public bool RequireVerifiedEmail { get; set; }

        [JsonProperty("require_verified_phone", NullValueHandling = NullValueHandling.Ignore)]
        public bool RequireVerifiedPhone { get; set; }

        [JsonProperty("require_min_past_trades", NullValueHandling = NullValueHandling.Ignore)]
        public object RequireMinPastTrades { get; set; }

        [JsonProperty("show_only_trusted_user", NullValueHandling = NullValueHandling.Ignore)]
        public bool ShowOnlyTrustedUser { get; set; }

        [JsonProperty("require_verified_id", NullValueHandling = NullValueHandling.Ignore)]
        public bool RequireVerifiedId { get; set; }

        [JsonProperty("require_offer_currency_match_buyer_country", NullValueHandling = NullValueHandling.Ignore)]
        public bool RequireOfferCurrencyMatchBuyerCountry { get; set; }

        [JsonProperty("payment_method_country_name", NullValueHandling = NullValueHandling.Ignore)]
        public object PaymentMethodCountryName { get; set; }

        [JsonProperty("new_buyer_max_fiat_limit")]
        public object NewBuyerMaxFiatLimit { get; set; }

        [JsonProperty("city_name", NullValueHandling = NullValueHandling.Ignore)]
        public object CityName { get; set; }

        [JsonProperty("country_name", NullValueHandling = NullValueHandling.Ignore)]
        public string CountryName { get; set; } = "";

        [JsonProperty("geoname_id", NullValueHandling = NullValueHandling.Ignore)]
        public object GeonameId { get; set; }

        [JsonProperty("last_seen", NullValueHandling = NullValueHandling.Ignore)]
        public string LastSeen { get; set; }

        [JsonProperty("last_seen_timestamp", NullValueHandling = NullValueHandling.Ignore)]
        public object LastSeenTimestamp { get; set; }

        [JsonProperty("offer_link")]
        public Uri OfferLink { get; set; }

        [JsonProperty("offer_owner_country_iso", NullValueHandling = NullValueHandling.Ignore)]
        public string OfferOwnerCountryIso { get; set; }

        [JsonProperty("offer_owner_feedback_negative")]
        public long OfferOwnerFeedbackNegative { get; set; }

        [JsonProperty("offer_owner_feedback_positive")]
        public long OfferOwnerFeedbackPositive { get; set; }

        [JsonProperty("offer_owner_profile_link")]
        public Uri OfferOwnerProfileLink { get; set; }

        [JsonProperty("offer_owner_username")]
        public string OfferOwnerUsername { get; set; }

        [JsonProperty("payment_window")]
        public int PaymentWindow { get; set; }

        [JsonProperty("release_time_median", NullValueHandling = NullValueHandling.Ignore)]
        public object ReleaseTimeMedian { get; set; }

        [JsonProperty("subdivision_name", NullValueHandling = NullValueHandling.Ignore)]
        public object SubdivisionName { get; set; }

        [JsonProperty("tags")]
        public List<object> Tags { get; set; }

        [JsonProperty("currency_code")]
        public string CurrencyCode { get; set; }

        [JsonProperty("fiat_currency_code")]
        public string FiatCurrencyCode { get; set; }

        [JsonProperty("is_blocked", NullValueHandling = NullValueHandling.Ignore)]
        public object IsBlocked { get; set; }

        [JsonProperty("payment_method_group", NullValueHandling = NullValueHandling.Ignore)]
        public string PaymentMethodGroup { get; set; }

        [JsonProperty("duty_hours")]
        public List<DutyHour> DutyHours { get; set; }

        [JsonProperty("crypto_currency")]
        public string CryptoCurrency { get; set; }

        [JsonProperty("created_at")]
        public long CreatedAt { get; set; }

        [JsonProperty("updated_at")]
        public long UpdatedAt { get; set; }
    }

    public partial class DutyHour
    {
        [JsonProperty("day")]
        public long Day { get; set; }

        [JsonProperty("active")]
        public long Active { get; set; }

        [JsonProperty("start_time")]
        public string StartTime { get; set; }

        [JsonProperty("end_time")]
        public string EndTime { get; set; }
    }

    public partial class OfferJson
    {
        public static OfferJson FromJson(string json) => JsonConvert.DeserializeObject<OfferJson>(json, Aggregator.Services.Paxful.Json.OfferJson.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this OfferJson self) => JsonConvert.SerializeObject(self, Aggregator.Services.Paxful.Json.OfferJson.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
